
name: Pushing artifact to jfrog

on:
    push:
      branches:
        - "main"

jobs:
    artifactoryUpload:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1.2.0
        - name: Publish to artifactory
          # uses: advancedcsg-open/action-jfrog-cli@master
          # with:
          #    url: 'https://artifactory.ssrcdevops.tii.'
          #    credentials type: 'apikey'
          #    apikey: ${{secrets.RT_APIKEY}}
          #    args: u "debian-handbook.pdf" "artifactory/github_actions_testing/" --recursive=true --build-name=pdf-build 
          uses: "jfrog/setup-jfrog-cli@v2"
        - name: Version check
          run: jf -v
        - name: Setting up jf cli with username and api key
          env: 
              APIKEY: ${{secrets.RT_APIKEY}}
          run: |
              jf c add --url https://artifactory.ssrcdevops.tii.ae:443 --user amal45 --password "$APIKEY"
              jf c show
              jf rt ping 
              jf rt u "data/file/*" github_actions_testing/
   